<a href="https://colab.research.google.com/github/ingridcos/Desafio-SQL-II/blob/main/Python_para_Dados_Atividade_de_Fixa%C3%A7%C3%A3o_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# 1. Array 4x3 aleatório
arr1 = np.random.rand(4, 3)
print("1. Array 4x3 aleatório:\n", arr1, "\n")

1. Array 4x3 aleatório:
 [[0.1008956  0.58627822 0.64725066]
 [0.76999962 0.97894606 0.93819558]
 [0.58323021 0.83313112 0.8390166 ]
 [0.24248148 0.50542252 0.32469683]] 



In [3]:
# 2. Array 3x5 inteiros aleatórios (0-10)
arr2 = np.random.randint(0, 11, size=(3, 5))
print("2. Array 3x5 inteiros:\n", arr2, "\n")

2. Array 3x5 inteiros:
 [[2 5 5 8 3]
 [5 5 6 7 9]
 [9 1 1 6 6]] 



In [4]:
# 3. Array 10x5 zeros
arr3 = np.zeros((10, 5))
print("3. Array 10x5 zeros:\n", arr3[:2], "...", "\n")  # Mostra só primeiras 2 linhas

3. Array 10x5 zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] ... 



In [5]:
# 4. Array 0-90 de 4 em 4
arr4 = np.arange(0, 91, 4)
print("4. Array 0-90 (passo 4):\n", arr4, "\n")

4. Array 0-90 (passo 4):
 [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88] 



In [6]:
# 5. Reduzir array 5x7 para 1D
arr5 = np.random.rand(5, 7)
arr5_1d = arr5.ravel()
print("5. Array 5x7 -> 1D:\n", arr5_1d[:10], "...", "\n")

5. Array 5x7 -> 1D:
 [0.0571222  0.39936355 0.89002336 0.45903815 0.56832601 0.21728898
 0.98527252 0.10952531 0.00683542 0.46259292] ... 



In [7]:
import numpy as np

# 6) 10 participantes, 12 números por cartela (1 a 30)
bingo = np.random.randint(1, 31, size=10*12)  # 120 números (1D)
print("Shape bingo 1D:", bingo.shape)

# opcional: ver a “versão original” em 10 cartelas 4x3
bingo_10_4x3 = bingo.reshape(10, 4, 3)
print("Shape 10 cartelas 4x3:", bingo_10_4x3.shape)

# 7) reshape para 5 cartelas de 4 linhas e 6 colunas
bingo_5_4x6 = bingo.reshape(5, 4, 6)
print("Shape 5 cartelas 4x6:", bingo_5_4x6.shape)
print("Primeira cartela 4x6:\n", bingo_5_4x6[0])

Shape bingo 1D: (120,)
Shape 10 cartelas 4x3: (10, 4, 3)
Shape 5 cartelas 4x6: (5, 4, 6)
Primeira cartela 4x6:
 [[24 20 17 20  6 13]
 [14 23  9 14 24 22]
 [29  7  6  1 23 15]
 [ 5  7 11 17 30  7]]


In [8]:
# 6. Bingo: 10 cartelas (12 números cada, 1-30) - shape (10, 4, 3)
bingo = np.random.randint(1, 31, size=(10, 4, 3))
print("6. Bingo 10 cartelas (4x3):\n", bingo[0], "\n")  # Primeira cartela

# 7. Reshape para 5 cartelas 4x6
bingo_reshaped = bingo.reshape(5, 4, 6) # Removed the [:5] slice
print("7. 5 cartelas 4x6:\n", bingo_reshaped[0], "\n")

6. Bingo 10 cartelas (4x3):
 [[13 19 26]
 [22  5 26]
 [16 17 20]
 [ 7 16  2]] 

7. 5 cartelas 4x6:
 [[13 19 26 22  5 26]
 [16 17 20  7 16  2]
 [14 26 19 11 14  1]
 [15 16 15  9 17 26]] 



In [9]:
print("=== MANIPULANDO ARRAYS - ECOSSISTEMAS ===\n")

# Array espécies (ID, qtd, profundidade, tamanho) - reconstruído do PDF
especies = np.array([
    [747, 89, 33, 5], [623, 123, 32, 13], [501, 22, 49, 2], [116, 101, 42, 10],
    [297, 56, 69, 22], [613, 64, 27, 7], [295, 84, 29, 14], [692, 105, 72, 16],
    [229, 103, 35, 5], [374, 124, 70, 1]
])
print("Array espécies original:\n", especies, "\n")

=== MANIPULANDO ARRAYS - ECOSSISTEMAS ===

Array espécies original:
 [[747  89  33   5]
 [623 123  32  13]
 [501  22  49   2]
 [116 101  42  10]
 [297  56  69  22]
 [613  64  27   7]
 [295  84  29  14]
 [692 105  72  16]
 [229 103  35   5]
 [374 124  70   1]] 



In [10]:
# 1a. Segunda coluna (quantidade)
qtd_especies = especies[:, 1]
print("1a. Quantidade de espécies:", qtd_especies, "\n")

1a. Quantidade de espécies: [ 89 123  22 101  56  64  84 105 103 124] 



In [11]:
# 1b. Primeiras 3 quantidades
print("1b. Primeiras 3 quantidades:", qtd_especies[:3], "\n")

1b. Primeiras 3 quantidades: [ 89 123  22] 



In [12]:
# 1c. Últimas 5 quantidades
print("1c. Últimas 5 quantidades:", qtd_especies[-5:], "\n")


1c. Últimas 5 quantidades: [ 64  84 105 103 124] 



In [13]:
# 1d. Tamanhos ordenados
tamanhos = especies[:, 3]
tamanhos_ordenados = np.sort(tamanhos)
print("1d. Tamanhos ordenados:", tamanhos_ordenados, "\n")

1d. Tamanhos ordenados: [ 1  2  5  5  7 10 13 14 16 22] 



In [14]:
# 2a. Index boolean - maior espécie (tamanho == 22)
maior_especie = especies[especies[:, 3] == 22]
print("2a. Maior espécie (tamanho 22):\n", maior_especie, "\n")

2a. Maior espécie (tamanho 22):
 [[297  56  69  22]] 



In [15]:
# 2b. Fancy index - ID 297
id_297 = especies[especies[:, 0] == 297]
print("2b. Espécie ID 297:\n", id_297, "\n")

2b. Espécie ID 297:
 [[297  56  69  22]] 



In [16]:
# 2c. np.where - qtd 105
idx_105 = np.where(especies[:, 1] == 105)
linha_105 = especies[idx_105]
print("2c. Espécie com 105 representantes:\n", linha_105, "\n")

2c. Espécie com 105 representantes:
 [[692 105  72  16]] 



In [17]:
# 2d. Profundidade > 60 = "Profundo"

# garante que especies existe antes deste trecho
# print(especies)
# print(especies.dtype)

# pega a coluna de profundidade e transforma em objeto (aceita int + str)
profundidade = especies[:, 2].astype(object)
profundidade[profundidade.astype(int) > 60] = "Profundo"

# copia o array original, mas como object para aceitar texto
especies_copy = especies.astype(object)
especies_copy[:, 2] = profundidade

print("2d. Profundidade (>60 = Profundo):\n", especies_copy[:, 2], "\n")


2d. Profundidade (>60 = Profundo):
 [33 32 49 42 'Profundo' 27 29 'Profundo' 35 'Profundo'] 



In [18]:
# 3a. Adicionar 2 novas espécies
novas_especies = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])
especies_expandida = np.vstack([especies, novas_especies])
print("3a. +2 espécies (primeiras 5):\n", especies_expandida[:5], "\n")

3a. +2 espécies (primeiras 5):
 [[747  89  33   5]
 [623 123  32  13]
 [501  22  49   2]
 [116 101  42  10]
 [297  56  69  22]] 



In [19]:
# 3b. Nova coluna visão [0,1,0,0,0,0,1,0,1,1,0]
# essa lista tem que ter o MESMO número de linhas do array
visao = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1])  # para 10 linhas
# se você tiver 11 linhas, use:
# visao = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0])

# empilha a nova coluna no array com profundidade tratada
especies_com_visao = np.column_stack([especies_copy, visao])

print("3b. + Coluna visão (primeiras 3 linhas):\n", especies_com_visao[:3], "\n")

3b. + Coluna visão (primeiras 3 linhas):
 [[747 89 33 5 0]
 [623 123 32 13 1]
 [501 22 49 2 0]] 



In [20]:
# Array acidentes
acidentes = np.array([1, 3, 2, 0, 1, 0, 2, 1, 4, 0, 0, 0, 1, 1, 0])
print("Acidentes:", acidentes, "\n")

Acidentes: [1 3 2 0 1 0 2 1 4 0 0 0 1 1 0] 



In [21]:
# 1. Clientes abaixo da média
media_acidentes = np.mean(acidentes)
desconto = acidentes[acidentes < media_acidentes]
print("1. Abaixo da média (", round(media_acidentes, 2), "):", desconto, "\n")

1. Abaixo da média ( 1.07 ): [1 0 1 0 1 0 0 0 1 1 0] 



In [22]:
#2. índices (clientes) que tiveram pelo menos 2 anos sem acidentes
clientes_2_anos_sem = np.where(acidentes == 0)[0]  # aqui são todos que tiveram 0 pelo menos 1 vez

print("2. Clientes com pelo menos 1 ano sem acidentes (zeros):", clientes_2_anos_sem, "\n")

2. Clientes com pelo menos 1 ano sem acidentes (zeros): [ 3  5  9 10 11 14] 



In [23]:
# 3. Função 3x - 2y + xy (exemplo arrays)
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
resultado = 3*x - 2*y + x*y
print("3. 3x-2y+xy:", resultado, "\n")

3. 3x-2y+xy: [-1  6 15] 



In [24]:
# 4. Adicionar notas grupo [1, 2, 1] às provas
# cada linha = 1 estudante, cada coluna = 1 prova
notas_provas = np.array([
    [5, 6, 7],
    [8, 9, 10],
    [7, 8, 9]
])

# mesma nota de trabalho por prova: 1, 2, 1
notas_grupo = np.array([1, 2, 1])

print("Shape notas_provas:", notas_provas.shape)  # (3, 3)
print("Shape notas_grupo:", notas_grupo.shape)    # (3,)

# broadcasting: soma o vetor [1,2,1] em cada linha
notas_finais = notas_provas + notas_grupo

print("4. Notas finais + grupo:\n", notas_finais, "\n")

Shape notas_provas: (3, 3)
Shape notas_grupo: (3,)
4. Notas finais + grupo:
 [[ 6  8  8]
 [ 9 11 11]
 [ 8 10 10]] 

